config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' ,registrations: 'users/registrations'}
  resources :events, only: %i[index new create show]
  resources :tickets, only: %i[create]
  resources :users, only: :show
  delete '/tickets', to: "tickets#destroy"
  root "static_pages#home"
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :tickets
  has_many :attendees, through: :tickets
  belongs_to :creator, class_name: :User

  validates :description, presence: true
  validates :date, presence: true

  scope :upcoming, -> { where('date > ?', DateTime.now) }
  scope :past, -> { where('date < ?', DateTime.now) }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    if signed_in?
      @past_events = Event.past
      @upcoming_events = Event.upcoming
    else
      flash[:warning] = 'Please sign in'
      redirect_to root_path
    end
  end

  def new
    @event = current_user.events.build
  end

  def create
    date = event_params[:date].to_datetime.strftime('%Y/%m/%d %H:%M')
    @event = current_user.events.build(date: date, description: event_params[:description])
    if @event.save
      Ticket.create(attendee_id: current_user.id, event_id: @event.id)
      redirect_to @event
    else
      render :new
    end
  end

  def show
    @event = Event.find_by(id: params[:id])
  end

  private

  def event_params
    params.require(:event).permit(:description, :date)
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def me?(user)
    user == current_user
  end

  def my_event?(event)
    me?(event.creator)
  end

  def others_event?(event)
    !my_event? event
  end

  def event_creator(event)
    my_event?(event) ? 'me' : event.creator.name
  end

  def attending?(event)
    event.attendees.include?(current_user)
  end

  def event_ticket(event)
    { event_id: event.id, attendee_id: current_user.id }
  end
end

app/views/events/_event.html.erb
<div>
  <hr>
  <p>
    <h3><%=event.id  %>:
      <%= event.description %>
    </h3>
    <%  %>
  </p>
  <p>
    Created by <%= event_creator(event)%>
  </p>
  <% past = past || false %>
  <% if !attending?(event) && !past %>
    <%= link_to 'Attend',tickets_path(ticket: event_ticket(event)), method: :post ,class:"btn bg-success text-white"%>
  <% elsif attending?(event) && !past%>
    <strong>You are attending.</strong>
    <br>
    <br>
    <%= link_to 'Cancel',tickets_path(ticket: event_ticket(event)), method: :delete ,class:"btn bg-success text-white" %>
  <% end %>
  <%= link_to 'Show', event ,class:"btn bg-success text-white"%>
  <hr>
</div>

app/views/events/index.html.erb
<% if @upcoming_events.any? %>
  <h3>Upcoming events</h3>
  <%= render @upcoming_events %>
<% end %>
<% if @past_events.any? %>
  <h3>Past events</h3>
  <%= render @past_events, past: true %>
<% end %>

app/views/events/new.html.erb
  <%= render 'layouts/shared/error_messages', resource:@event %>
<%= form_with model: @event, local: true do |form|%>
  <%= form.label :description %>
  <br>
  <%= form.text_field :description %>
  <br>
  <%= form.label :date %>
  <br>
  <%= form.datetime_field :date %>
  <br>
  <br>
  <%= form.submit "Submit", class:"btn btn-success btn-sm" %>
<% end %>

app/views/events/show.html.erb
<h1>Event: <%= @event.id %></h1>
<h2>created by <%= event_creator(@event)%></h2>
<br>
<h3><%= @event.description %></h3>
<br>
<p>
  Time:  <%= @event.date %>
</p>
<h3>Attendees</h3>
<ul>
  <% @event.attendees.each do |attendee| %>
    <li>
      <% if me?(attendee) %>
        <%= "Me" %>
      <% else %>
        <%= attendee.name %>
      <% end %>
    </li>
  <% end %>
</ul>