config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' ,registrations: 'users/registrations'}
  resources :events, only: %i[index new create show]
  resources :tickets, only: %i[create]
  resources :users, only: :show
  delete '/tickets', to: "tickets#destroy"
  root "static_pages#home"
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-success">
  <%= link_to 'Private events ', root_path,class:'nav-link text-white navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Events', events_path,class:'nav-link  text-white' %>
      </li>
      <% if signed_in? %>
        <li>   <%= link_to current_user.name, current_user,class:'nav-link  text-white' %></li>
        <li class="nav-item">
          <%= link_to 'Settings', edit_user_registration_path,class:'nav-link  text-white' %>
        </li>
        <li class="nav-item">
          <%= link_to 'New event', new_event_path,class:'nav-link  text-white' %>
        </li>
        <li class="nav-item">
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'text-white nav-link' %>
        </li>
      <% else %>
        <li class="nav-item active">
          <%= link_to 'Sign up', new_user_registration_path,class:'nav-link text-white' %>
        </li>
        <li class="nav-item active">
          <%= link_to 'Log in', new_user_session_path,class:'nav-link text-white' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type,message| %>
        <% message_type = message_type == "notice" ? "info" : message_type%>
        <% message_type = message_type == "alert" ? "warning" : message_type%>
        <%= content_tag :div, message, class:"alert alert-#{message_type}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>